# Site settings
title: Chetty Arun
email: me@chettyarun.com
description: "Blog of Chetty Arun. Biotech Undergrad // Graphic Designer // UI/UX Enthusiast"
baseurl: "/blog"
url: "http://chettyarun.in"
twitter_username: chettyarun
github_username:  chettyarun
facebook_username:  chetty.arun.nani

# Build settings
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
markdown: kramdown
pygments: null
highlighter: rouge